#!/usr/bin/env bash
# Generic Vortex Agent installer (credentials via env).
# Prefer the personalized script generated by Vortex Web (Install agent).
set -euo pipefail

: "${VORTEX_CORE_URL:?set VORTEX_CORE_URL}"
: "${VORTEX_AGENT_ID:?set VORTEX_AGENT_ID}"
: "${VORTEX_SECRET_TOKEN:?set VORTEX_SECRET_TOKEN}"

BIN_PATH="${VORTEX_BIN_PATH:-/usr/local/bin/vortex-agent}"
ENV_PATH="${VORTEX_ENV_PATH:-/etc/vortex-agent.env}"
UNIT_PATH="${VORTEX_UNIT_PATH:-/etc/systemd/system/vortex-agent.service}"
BINARY_BASE="${VORTEX_AGENT_BINARY_BASE_URL:-}"

need_root() {
  if [[ "${EUID}" -ne 0 ]]; then
    echo "re-run as root (sudo)" >&2
    exit 1
  fi
}

detect_asset() {
  local os arch
  os="$(uname -s | tr '[:upper:]' '[:lower:]')"
  arch="$(uname -m)"
  case "${arch}" in
    x86_64|amd64) arch="amd64" ;;
    aarch64|arm64) arch="arm64" ;;
    *) echo "unsupported arch: ${arch}" >&2; exit 1 ;;
  esac
  case "${os}" in
    linux) echo "vortex-agent-linux-${arch}" ;;
    darwin) echo "vortex-agent-darwin-${arch}" ;;
    *) echo "unsupported os: ${os}" >&2; exit 1 ;;
  esac
}

install_binary() {
  if [[ -x "${BIN_PATH}" && -z "${BINARY_BASE}" ]]; then
    echo "using existing binary at ${BIN_PATH}"
    return
  fi
  if [[ -z "${BINARY_BASE}" ]]; then
    echo "VORTEX_AGENT_BINARY_BASE_URL is empty — place binary at ${BIN_PATH} manually" >&2
    if [[ ! -x "${BIN_PATH}" ]]; then
      exit 1
    fi
    return
  fi
  local asset url tmp
  asset="$(detect_asset)"
  url="${BINARY_BASE%/}/${asset}"
  tmp="$(mktemp)"
  echo "downloading ${url}"
  curl -fsSL "${url}" -o "${tmp}"
  install -Dm755 "${tmp}" "${BIN_PATH}"
  rm -f "${tmp}"
}

write_env() {
  umask 077
  cat >"${ENV_PATH}" <<EOF
VORTEX_CORE_URL=${VORTEX_CORE_URL}
VORTEX_AGENT_ID=${VORTEX_AGENT_ID}
VORTEX_SECRET_TOKEN=${VORTEX_SECRET_TOKEN}
VORTEX_LOG_LEVEL=info
EOF
  chmod 600 "${ENV_PATH}"
  echo "wrote ${ENV_PATH}"
}

write_unit() {
  cat >"${UNIT_PATH}" <<'EOF'
[Unit]
Description=Vortex Agent — outbound tunnel to Vortex Core
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
EnvironmentFile=-/etc/vortex-agent.env
ExecStart=/usr/local/bin/vortex-agent
Restart=always
RestartSec=2
NoNewPrivileges=true

[Install]
WantedBy=multi-user.target
EOF
}

enable_service() {
  if command -v systemctl >/dev/null 2>&1; then
    systemctl daemon-reload
    systemctl enable --now vortex-agent
    systemctl --no-pager --full status vortex-agent || true
  else
    echo "systemctl not found — start manually: ${BIN_PATH}"
    nohup "${BIN_PATH}" >/var/log/vortex-agent.log 2>&1 &
  fi
}

need_root
install_binary
write_env
write_unit
enable_service
echo "Vortex Agent enrolled (agent_id=${VORTEX_AGENT_ID})"
